# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package -DskipTests --file pom.xml
    
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
 
        name: javacode
        path: target
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
         HOST: ec2-34-229-232-99.compute-1.amazonaws.com
         USERNAME: ec2-user
         PORT: 22
         KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
        with:
         source: "/home/runner/work/IAC-REST/IAC-REST/javacode/"
         target: "/home/ec2-user/cicd/"
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ec2-34-229-232-99.compute-1.amazonaws.com
          USERNAME: ec2-user
          PORT: 22
          KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          script: nohup java -jar /home/ec2-user/cicd/github/workspace/javacode/*.jar &
  
   
   
  
